
baseURL = 'http://pharaoh.local'
languageCode = 'en-us'
title = 'MindMap'
theme = "shadocs"
themesDir = "../themes"

[markup]
  defaultMarkdownHandler = 'goldmark'

  [markup.tableOfContents]
    endLevel = 7
    ordered = false
        