
baseURL = 'http://pharaoh.local'
languageCode = 'en-us'
title = 'MindMap'
theme = "relearn"
themesDir = "../themes"

[params]
    themeVariant = "relearn-dark"
    disableToc = false
    disableSearch = false

[markup]
  [markup.tableOfContents]
    endLevel = 7
    ordered = false
        